# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Update Repo URL in QMD
        run: |
          QMD_FILE="vignettes/articles/cascading_inputs.qmd"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            sed -i "s|__SHINYBATCH_REPO_URL__|https://shinybatch.shinyworks.io/pr/${{ github.event.number }}|g" $QMD_FILE
          else
            sed -i "s|__SHINYBATCH_REPO_URL__|https://shinybatch.shinyworks.io/|g" $QMD_FILE
          fi

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      # Build the local R package and structure the CRAN repository
      - name: Build Wasm R packages
        uses: r-wasm/actions/build-rwasm@v2
        with:
          r-version: '4.4'
          packages: |
            shiny
            "."
          repo-path: "docs"
  
      # Upload an artifact that will work with GitHub Pages
      - name: Upload Pages artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs"
          
      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs

      - name: Deploy PR preview 🧪
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          # Don't clean the whole branch, just the target folder
          clean: false
          branch: gh-pages
          folder: docs
          # Deploy to a subdirectory named after the PR number
          target-folder: pr/${{ github.event.number }}
